routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Auth
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::namespace('Admin')
    ->name('admin.')
    ->prefix('admin')
    ->middleware('auth')
    ->group(function () {
        Route::get('/', 'AdminController@index')->name('index');

        Route::resource('posts', 'PostsController');
        Route::resource('users', 'UsersController');

        Route::get('images/random', 'PostsController@randomImage')->name('images.random'); // @todo Move to AdminController
    });

Route::get('/', 'PostController@index')->name('posts.index');
Route::get('/{post}', 'PostController@show')->name('posts.show');

resources/views/pages/admin/index.blade.php
@extends('layouts.app')

@section('title')
    Admin
@endsection

@section('content')
    @include('components.messages')

    <h1>Admin</h1>

    @include('components.breadcrumbs', ['links' => [
        'Admin' => route('admin.index'),
    ]])

    <div class="card-deck admin-cards">
        <a href="{{route('admin.users.index')}}">
            <div class="card text-white bg-primary mb-3">
                <div class="card-body">
                    <h5 class="card-title">Users</h5>
                    <p class="card-text">{{$users}}</p>
                </div>
            </div>
        </a>

        <a href="{{route('admin.posts.index')}}">
            <div class="card text-white bg-info mb-3">
                <div class="card-body">
                    <h5 class="card-title">Posts</h5>
                    <p class="card-text">{{$posts}}</p>
                </div>
            </div>
        </a>

    </div>


@endsection