routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Auth
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::namespace('Admin')
    ->name('admin.')
    ->prefix('admin')
    ->middleware('auth')
    ->group(function () {
        Route::get('/', 'AdminController@index')->name('index');

        Route::resource('posts', 'PostsController');
        Route::resource('users', 'UsersController');

        Route::get('images/random', 'PostsController@randomImage')->name('images.random'); // @todo Move to AdminController
    });

Route::get('/', 'PostController@index')->name('posts.index');
Route::get('/{post}', 'PostController@show')->name('posts.show');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Jenssegers\Mongodb\Eloquent\HybridRelations;

/**
 * App\User
 *
 * @property int $id
 * @property string $name
 * @property string $email
 * @property string $password
 * @property string|null $remember_token
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read \Illuminate\Notifications\DatabaseNotificationCollection|\Illuminate\Notifications\DatabaseNotification[] $notifications
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Post[] $posts
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereEmail($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User wherePassword($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereRememberToken($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\User whereUpdatedAt($value)
 * @mixin \Eloquent
 */
class User extends Authenticatable
{
    use Notifiable;
    use HybridRelations;

    protected $connection = 'mysql';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function posts()
    {
        return $this->hasMany(Post::class);
    }
}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Validation\Rule;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::paginate();

        return view('pages/admin/users/index', ['users' => $users]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages/admin/users/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => ['required', 'string', 'max:100'],
            'email' => ['required', 'email', Rule::unique('mysql.users', 'email')],
            'password' => ['nullable', 'string', 'min:6', 'confirmed'],
        ]);

        $user = new User();
        $user->fill($request->all());
        $user->save();

        return redirect()->route('admin.users.index')->with('message', "User has been created");
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view('pages/admin/users/show', ['user' => $user]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('pages/admin/users/edit', ['user' => $user]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $this->validate($request, [
            'name' => ['required', 'string', 'max:100'],
            'email' => ['required', 'email', Rule::unique('mysql.users', 'email')->ignore($user->email, 'email')],
            'password' => ['nullable', 'string', 'min:6', 'confirmed'],
        ]);

        $user->name = $request->input('name');
        $user->email = $request->input('email');

        if ($request->input('password')) {
            // User supplied a password, so update it
            $user->password = $request->input('password');
        }

        $user->save();

        return redirect()->route('admin.users.index')->with('message', "User has been updated");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();

        return redirect()->route('admin.users.index')->with('message', "User has been deleted");

    }
}

resources/views/pages/admin/users/create.blade.php
@extends('layouts.app')

@section('title')
    Create User
@endsection

@section('content')

    <h3>Create user</h3>

    @include('components.breadcrumbs', ['links' => [
        'Admin' => route('admin.index'),
        'Users' => route('admin.users.index'),
        'Create' => route('admin.users.create'),
    ]])

    @include('components.errors')

    @include('components.user-form', ['url' => route('admin.users.store'), 'method' => 'post', 'action' => 'create'])
@endsection

resources/views/pages/admin/users/edit.blade.php
@extends('layouts.app')

@section('title')
    Edit User &raquo; {{$user->name}}
@endsection

@section('content')

    <h3>Edit user: {{$user->name}}</h3>

    @include('components.breadcrumbs', ['links' => [
        'Admin' => route('admin.index'),
        'Users' => route('admin.users.index'),
        $user->name => route('admin.users.edit', $user),
    ]])

    @include('components.errors')

    @include('components.user-form', ['url' => route('admin.users.update', $user), 'method' => 'patch', 'action' => 'edit'])
@endsection

resources/views/pages/admin/users/index.blade.php
@extends('layouts.app')

@section('content')
    @include('components.messages')

    <h2>Users</h2>

    @include('components.breadcrumbs', ['links' => [
        'Admin' => route('admin.index'),
        'Users' => route('admin.users.index'),
    ]])

    <a href="{{route('admin.users.create')}}" class="btn btn-primary mb-3">Create User</a>

    @if (count($users) > 0)
        <table class="table table-bordered table-striped">
            <thead>
            <tr>
                <th>Name</th>
                <th>Email Address</th>
                <th>Created</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            @foreach ($users as $user)
                <tr>
                    <td><a href="{{route('admin.users.show', $user)}}">{{$user->name}}</a></td>
                    <td>{{$user->email}}</td>
                    <td>{{$user->created_at}}</td>
                    <td>
                        <a href="{{ route('admin.users.edit', $user) }}" class="btn btn-outline-primary">Edit</a>
                        @if (Auth::user() != $user)
                            <form action="{{route('admin.users.destroy', $user)}}" method="post" class="d-inline-block">
                                {{-- @todo Confirmation --}}
                                {{ method_field('delete') }}
                                {{ csrf_field() }}
                                <input type="submit" value="Delete" class="btn btn-outline-danger">
                            </form>
                        @endif
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        {{ $users->links() }}
    @else
        <div class="alert alert-info">No users yet, so how did you log in?</div>
    @endif
@endsection

resources/views/pages/admin/users/show.blade.php
@extends('layouts.app')

@section('title')
    Admin &raquo; Users &raquo; {{$user->name}}
@endsection

@section('content')
    @include('components.messages')

    @include('components.breadcrumbs', ['links' => [
        'Admin' => route('admin.index'),
        'Users' => route('admin.users.index'),
        $user->name => route('admin.users.show', $user),
    ]])

    <div class="row mb-3">
        <div class="col-6 text-left">
            <a href="{{route('admin.users.index')}}" class="btn btn-outline-primary">Back to all users</a>
        </div>
        <div class="col-6 text-right">
            <a href="{{ route('admin.users.edit', $user) }}" class="btn btn-outline-primary">Edit</a>
            @if (Auth::user() != $user)
                <form action="{{route('admin.users.destroy', $user)}}" method="post" class="d-inline-block">
                    {{-- @todo Confirmation --}}
                    {{ method_field('delete') }}
                    {{ csrf_field() }}
                    <input type="submit" value="Delete" class="btn btn-outline-danger">
                </form>
            @endif
        </div>
    </div>

    <table class="table table-bordered">
        <tbody>
        <tr>
            <th>Name</th>
            <td>{{$user->name}}</td>
        </tr>
        <tr>
            <th>Email</th>
            <td>{{$user->email}}</td>
        </tr>
        <tr>
            <th>Created on</th>
            <td>{{$user->created_at}}</td>
        </tr>
        </tbody>
    </table>

    <h3>Posts by {{$user->name}}</h3>

    @if (count($user->posts) > 0)
        <table class="table table-bordered table-striped">
            <thead>
            <tr>
                <th>Title</th>
                <th>Post Date</th>
            </tr>
            </thead>
            <tbody>
            @foreach ($user->posts as $post)
                <tr>
                    <td><a href="{{route('admin.posts.show', $post)}}">{{$post->title}}<a/></td>
                    <td>{{$post->post_at}}</td>
                </tr>
            @endforeach
            </tbody>
        </table>
    @else
        <div class="alert alert-info">This user hasn't created any posts yet</div>
    @endif
@endsection