routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Auth
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::namespace('Admin')
    ->name('admin.')
    ->prefix('admin')
    ->middleware('auth')
    ->group(function () {
        Route::get('/', 'AdminController@index')->name('index');

        Route::resource('posts', 'PostsController');
        Route::resource('users', 'UsersController');

        Route::get('images/random', 'PostsController@randomImage')->name('images.random'); // @todo Move to AdminController
    });

Route::get('/', 'PostController@index')->name('posts.index');
Route::get('/{post}', 'PostController@show')->name('posts.show');

app/Post.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Concerns\HasTimestamps;
use Jenssegers\Mongodb\Eloquent\Model;
use Jenssegers\Mongodb\Eloquent\SoftDeletes;
use Jenssegers\Mongodb\Eloquent\Builder;
use League\CommonMark\CommonMarkConverter;

class Post extends Model
{
    use HasTimestamps;
    use SoftDeletes;

    protected $connection = 'mongodb';
    protected $collection = 'posts';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
        'post_at',
    ];

    protected $primaryKey = 'slug';

    protected $fillable = [
        'title',
        'slug',
        'content',
        'post_at',
        'banner',
    ];

    public static function boot()
    {
        parent::boot();

        static::addGlobalScope(function(\Illuminate\Database\Eloquent\Builder $builder) {
            $builder->orderBy('post_at', 'desc');
        });

        static::saving(function (self $model) {
            if ($model->slug === null) {
                $model->slug = str_slug($model->title);
            }

            if ($model->post_at === null) {
                $model->post_at = Carbon::now();
            }
        });
    }

    /**
     * Convert the user input into HTML from Markdown, and save alongside
     * @param string $value
     */
    public function setContentAttribute(string $value)
    {
        $this->attributes['markdown'] = $value;

        $this->attributes['html'] = (new CommonMarkConverter(['html_input' => 'escape']))->convertToHtml($value);
    }

    public function getContentAttribute()
    {
        return $this->attributes['markdown'] ?? null;
    }

    public function scopePublished(Builder $query)
    {
        $query->where('post_at', '<=', Carbon::now());
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/Admin/PostsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\PostRequest;
use App\Post;
use GuzzleHttp\Client;
use GuzzleHttp\Exception\RequestException;
use Illuminate\Support\Str;
use Illuminate\Validation\Rule;

class PostsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::has('user')->with('user')->paginate();

        return view('pages/admin/posts/index', ['posts' => $posts]);
    }

    public function randomImage()
    {
        /*
         * Need to access the URL, then return the URL after redirects
         */
        $url = 'https://picsum.photos/1000/400/?random';

        $client = app(Client::class);

        try {
            $response = $client->get($url);

            $file = 'images/' . Str::random(16) . '.jpg';

            \Storage::disk('public')->put($file, $response->getBody(), 'public');

            return [
                'url' => \Storage::disk('public')->url($file),
            ];
        } catch (RequestException $e) {
            logger()->warning('Unable to fetch URL due to error', ['exception' => $e]);
            abort(500, 'Unable to get image at this time');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages/admin/posts/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(PostRequest $request)
    {
        $this->validate($request, [
            'slug' => [Rule::unique('mongodb.posts', 'slug')],
        ]);

        if ($request->has('file')) {
            $file = \Storage::disk('public')->putFile('images', $request->file('file'), 'public');
            $path = \Storage::disk('public')->url($file);
        } else {
            // Use the URL instead
            $path = $request->input('url');
        }

        $post = new Post();
        $post->fill([
            // We don't want a straight $request->all(), as we want to rename some parameters
            'title' => $request->input('title'),
            'slug' => $request->input('slug'),
            'content' => $request->input('post'),
            'post_at' => $request->input('postDate'),
            'banner' => $path,
        ]);
        $post->user()->associate(\Auth::user());

        $post->save();

        return redirect()->route('admin.posts.index')->with('message', "Post has been created");
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Post $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        return view('pages/admin/posts/show', ['post' => $post]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Post $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        return view('pages/admin/posts/edit', ['post' => $post]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Post $post
     * @return \Illuminate\Http\Response
     */
    public function update(PostRequest $request, Post $post)
    {
        $this->validate($request, [
            'slug' => [Rule::unique('mongodb.posts', 'slug')->ignore($post->_id, '_id')],
        ]);

        if ($request->has('file')) {
            $file = \Storage::disk('public')->putFile('images', $request->file('file'), 'public');
            $path = \Storage::disk('public')->url($file);
        } else {
            // Use the URL instead
            $path = $request->input('url');
        }

        $post->fill([
            // We don't want a straight $request->all(), as we want to rename some parameters
            'title' => $request->input('title'),
            'slug' => $request->input('slug'),
            'content' => $request->input('post'),
            'post_at' => $request->input('postDate'),
            'banner' => $path,
        ]);

        $post->save();

        return redirect()->route('admin.posts.index')->with('message', "Post has been updated");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Post $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        $post->delete();

        return redirect()->route('admin.posts.index')->with('message', "Post has been deleted");
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Post;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::published()->has('user')->with('user')->paginate(5);

        return view('pages/posts/index', ['posts' => $posts]);
    }

    public function show($slug)
    {
        $post = Post::published()->findOrFail($slug);

        return view('pages/posts/show', ['post' => $post]);
    }
}

resources/views/pages/admin/posts/create.blade.php
@extends('layouts.app')

@section('title')
    Create Post
@endsection

@section('content')

    <h3>Create a new post</h3>

    @include('components.breadcrumbs', ['links' => [
        'Admin' => route('admin.index'),
        'Posts' => route('admin.posts.index'),
        'Create' => route('admin.posts.create'),
    ]])

    @include('components.errors')

    @include('components.post-form', ['url' => route('admin.posts.store')])
@endsection

resources/views/pages/admin/posts/edit.blade.php
@extends('layouts.app')

@section('title')
    Edit Post &raquo; {{$post->title}}
@endsection

@section('content')

    <h3>Edit post: {{$post->title}}</h3>

    @include('components.breadcrumbs', ['links' => [
        'Admin' => route('admin.index'),
        'Posts' => route('admin.posts.index'),
        $post->title => route('admin.posts.edit', $post),
    ]])

    @include('components.errors')

    @include('components.post-form', ['url' => route('admin.posts.update', $post), 'method' => 'patch'])
@endsection

resources/views/pages/admin/posts/index.blade.php
@extends('layouts.app')

@section('content')
    @include('components.messages')

    <h2>Blog Posts</h2>

    @include('components.breadcrumbs', ['links' => [
        'Admin' => route('admin.index'),
        'Posts' => route('admin.posts.index'),
    ]])

    <a href="{{route('admin.posts.create')}}" class="btn btn-primary mb-3">Create Post</a>

    @if (count($posts) > 0)
        <table class="table table-bordered table-striped">
            <thead>
            <tr>
                <th>Title</th>
                <th>Post Date</th>
                <th>Author</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            @foreach ($posts as $post)
                <tr>
                    <td><a href="{{route('admin.posts.show', $post)}}">{{$post->title}}</a></td>
                    <td
                        @if ($post->post_at > \Illuminate\Support\Carbon::now())
                        class="bg-info"
                        title="Post not yet published"
                        @endif
                    >{{$post->post_at}}</td>
                    <td><a href="{{route('admin.users.show', $post->user)}}">{{$post->user->name}}</a></td>
                    <td>
                        <a href="{{ route('admin.posts.edit', $post) }}" class="btn btn-outline-primary">Edit</a>
                        <form action="{{route('admin.posts.destroy', $post)}}" method="post" class="d-inline-block">
                            {{-- @todo Confirmation --}}
                            {{ method_field('delete') }}
                            {{ csrf_field() }}
                            <input type="submit" value="Delete" class="btn btn-outline-danger">
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        {{ $posts->links() }}
    @else
        <div class="alert alert-info">No posts yet, why not <a href="{{route('admin.posts.create')}}">create</a> one?
        </div>
    @endif
@endsection

resources/views/pages/admin/posts/show.blade.php
@extends('layouts.app')

@section('title')
    Admin &raquo; Posts &raquo; {{$post->title}}
@endsection

@section('content')
    @include('components.messages')

    @include('components.breadcrumbs', ['links' => [
        'Admin' => route('admin.index'),
        'Posts' => route('admin.posts.index'),
        $post->title => route('admin.posts.show', $post),
    ]])

    <div class="row mb-3">
        <div class="col-6 text-left">
            <a href="{{route('admin.posts.index')}}" class="btn btn-outline-primary">Back to all posts</a>
        </div>
        <div class="col-6 text-right">
            <a href="{{ route('admin.posts.edit', $post) }}" class="btn btn-outline-primary">Edit</a>
            <form action="{{route('admin.posts.destroy', $post)}}" method="post" class="d-inline-block">
                {{-- @todo Confirmation --}}
                {{ method_field('delete') }}
                {{ csrf_field() }}
                <input type="submit" value="Delete" class="btn btn-outline-danger">
            </form>
        </div>
    </div>

    @include('components.post')
@endsection